#!/bin/sh
if [ -n "$WINDIR" ]; then
	exit
fi
exit=0
for file; do
	file="${file%/}"
	dir=`dirname "$file"`
	base=`basename "$file"`
	hidden="$dir/.$base"
	if [ -e "$hidden" -a -h "$file" -a "`readlink1 "$file"`" = ".$base" ]; then
		# already good
		continue
	fi
#	if [ -e "$hidden" ]; then
#		echo >&2 "$hidden" exists already
#		exit=1
#		continue
#	fi
	mv "$file" "$hidden"
	ln -s ".$base" "$file"
done
exit $exit
