# just for cleaning at the moment!

include ../.Make.conf

build:
	@echo examples are not built yet
clean:
	bk-clean
#	find . -type f \( -perm -u+x -o -perm -g+x -o -perm -o+x \) | xargs file | grep ELF | sed 's/:.*//' | xargs rm -f
