#!/bin/sh
exec perl -e '

use strict; use warnings; use L;

require "brace_parser.pl";

use Brace::HeaderExport;

our $text;
$text = slurp(\*STDIN);

brace_header_export(\@ARGV);

print $text;
' "$@"
