#!/bin/sh
exec perl -e '

use strict; use warnings; use L;

require "brace_parser.pl";

use Brace::SplitSemicolons;

our @lines;

read_lines(\*STDIN);

brace_split_semicolons(\@ARGV);

output_lines()
' "$@"
