#!/bin/sh
exec perl -e '

use strict; use warnings;
require "brace_parser.pl";

use Brace::Grep;

our @lines;

while (defined (my $file = <STDIN>)) {
	chomp $file;
	@lines = ();
	read_lines($file);
	brace_grep(@ARGV);
	for (@lines) {
		print "$file:$_";
	}
}
' "$@"
