#!/bin/sh
find . -type d -name .build >.tmp
<.tmp xargs rm -rf
rm .tmp
find . -type f \( -perm -u+x -o -perm -g+x -o -perm -o+x \) >.tmp
<.tmp grep -v '[/\\]\.' >.tmp.1
<.tmp.1 sed 's,.*/,&.,; s,^\./,,;' >.tmp.2
<.tmp.2 xargs rm -rf
rm .tmp .tmp.1 .tmp.2
find . -name '.*.b1' -o -name '.*.bb1' -o -name '.*.c' -o -name '.*.cc' -o -name '.*.log' -o -name '.*.exe' -o -name '.*.bak' -o -name '.*.bak2' -o -name '.*.xbak' -o -name '.*.lock' >.tmp
<.tmp xargs rm -rf
rm .tmp
rm -f mk.log mkfile.1 mkfile_cc headers.timestamp mk.failed
