#!/bin/sh
# make and test

fail() {
	echo fatal: "$@" >&2
	exit 1
}

mk || fail mk failed: not testing
grep "make: Nothing to be done for" ./.build/mk.log >/dev/null &&
	fail mk did nothing: not testing
grep "warning:" ./.build/mk.log >/dev/null &&
	fail mk gave warning/s: not testing
PROG=`find -maxdepth 1 -type f -perm +u+x |
xargs stat -c"%Y %n" | sort -rn |
head -n1 | cut -d' ' -f2`
exec "$PROG" "$@" # >/dev/tty 2>&1
